/**
 * activate.tsx — Staff Account Activation Route
 *
 * Landing page for invited staff members. The admin copies an invite link
 * (generated by Admin → Users → "Send Invite") and sends it to the new hire.
 *
 * URL: /activate?token=<signed_token>&tenant=<slug>
 *
 * Flow:
 *   1. On mount, GET /api/v1/auth/accept-invite/?token=... to validate token
 *      and pre-fill the user name / email.
 *   2. User enters their desired password and confirms it.
 *   3. POST /api/v1/auth/accept-invite/ with { token, new_password } to
 *      activate the account (INVITED → ACTIVE).
 *   4. On success, redirect to /login.
 */

import * as React from 'react';
import { createFileRoute, useRouter } from '@tanstack/react-router';
import { Eye, EyeOff, Loader2, CheckCircle2, ShieldCheck, XCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { BrandLogo } from '@/components/ui/BrandLogo';
import { fetchPublicBrandingApi, type PublicBrandingData } from '@/api/endpoints/api-platform';
import {
  validateInviteTokenApi,
  acceptInviteApi,
  type InviteInfoResponse as InviteInfo,
} from '@/api/endpoints/api-admin';

// ─── Route ───────────────────────────────────────────────────────────────────

export const Route = createFileRoute('/activate')({
  component: ActivatePage,
  head: () => ({
    meta: [
      { title: 'Activate Account — PerformanceOS' },
      { name: 'description', content: 'Set your password and activate your account' },
      { name: 'robots', content: 'noindex, nofollow' },
    ],
  }),
});

// ─── Password strength helper ─────────────────────────────────────────────────

function getStrength(pw: string): { score: number; label: string; color: string } {
  if (!pw) return { score: 0, label: '', color: '' };
  let score = 0;
  if (pw.length >= 8) score++;
  if (pw.length >= 12) score++;
  if (/[A-Z]/.test(pw)) score++;
  if (/[0-9]/.test(pw)) score++;
  if (/[^A-Za-z0-9]/.test(pw)) score++;
  if (score <= 1) return { score, label: 'Weak', color: '#ef4444' };
  if (score <= 2) return { score, label: 'Fair', color: '#f97316' };
  if (score <= 3) return { score, label: 'Good', color: '#eab308' };
  return { score, label: 'Strong', color: '#22c55e' };
}

// ─── Default branding fallback ────────────────────────────────────────────────

const DEFAULT_BRANDING: PublicBrandingData = {
  type: 'platform',
  app_name: 'PerformanceOS',
  brand_name: 'PerformanceOS',
  primary_color: '#0f766e',
  accent_color: '#2dd4bf',
  logo_url: '',
  favicon_url: '',
  login_tagline: 'Enterprise Operating System for Modern Athletic Franchises',
  support_email: '',
};

// ─── Component ────────────────────────────────────────────────────────────────

type Phase = 'loading' | 'ready' | 'submitting' | 'success' | 'error';

function ActivatePage() {
  const router = useRouter();

  // Read token & tenant from URL search params
  const search =
    typeof window !== 'undefined'
      ? new URLSearchParams(window.location.search)
      : new URLSearchParams();
  const token = search.get('token') ?? '';
  const tenantSlug = search.get('tenant') ?? '';

  // Branding
  const [branding, setBranding] = React.useState<PublicBrandingData>(DEFAULT_BRANDING);

  // Invite info
  const [inviteInfo, setInviteInfo] = React.useState<InviteInfo | null>(null);

  // Phase state machine
  const [phase, setPhase] = React.useState<Phase>('loading');
  const [tokenError, setTokenError] = React.useState<string | null>(null);

  // Form state
  const [password, setPassword] = React.useState('');
  const [confirm, setConfirm] = React.useState('');
  const [showPassword, setShowPassword] = React.useState(false);
  const [showConfirm, setShowConfirm] = React.useState(false);
  const [submitError, setSubmitError] = React.useState<string | null>(null);

  // ── Load branding ──────────────────────────────────────────────────────────
  React.useEffect(() => {
    const slug = tenantSlug.trim();
    fetchPublicBrandingApi(slug || undefined)
      .then(setBranding)
      .catch(() => setBranding(DEFAULT_BRANDING));
  }, [tenantSlug]);

  // Apply brand colours
  React.useEffect(() => {
    if (branding.primary_color) {
      document.documentElement.style.setProperty('--primary', branding.primary_color);
      document.documentElement.style.setProperty('--ring', branding.primary_color);
    }
    if (branding.accent_color) {
      document.documentElement.style.setProperty('--accent', branding.accent_color);
    }
  }, [branding.primary_color, branding.accent_color]);

  // ── Validate token on mount ────────────────────────────────────────────────
  React.useEffect(() => {
    if (!token) {
      setTokenError(
        'No invitation token found in this URL. Please use the exact link from your invitation email.',
      );
      setPhase('error');
      return;
    }

    validateInviteTokenApi(token)
      .then((info) => {
        setInviteInfo(info);
        if (info.status === 'ACTIVE') {
          void router.navigate({ to: '/login' });
          return;
        }
        setPhase('ready');
      })
      .catch((err: any) => {
        const msg: string =
          err?.response?.data?.error ?? err?.data?.error ?? 'Invalid or expired invitation link.';
        if (msg === 'expired') {
          setTokenError(
            'This invitation link has expired (links are valid for 72 hours). Please ask your admin to resend the invite.',
          );
        } else {
          setTokenError(msg.charAt(0).toUpperCase() + msg.slice(1));
        }
        setPhase('error');
      });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [token]);

  // ── Form submit ────────────────────────────────────────────────────────────
  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setSubmitError(null);

    if (password.length < 8) {
      setSubmitError('Password must be at least 8 characters.');
      return;
    }
    if (password !== confirm) {
      setSubmitError('Passwords do not match.');
      return;
    }

    setPhase('submitting');
    try {
      await acceptInviteApi(token, password);
      setPhase('success');
    } catch (err: any) {
      const msg: string =
        err?.response?.data?.error ??
        err?.data?.error ??
        'Something went wrong. Please try again.';
      setSubmitError(msg);
      setPhase('ready');
    }
  }

  // ── Derived values ─────────────────────────────────────────────────────────
  const primaryColor = branding.primary_color || '#0f766e';
  const accentColor = branding.accent_color || '#2dd4bf';
  const appName = branding.app_name || 'PerformanceOS';
  const logoUrl = branding.logo_url || '';
  const strength = getStrength(password);
  const passwordsMatch = confirm.length > 0 && password === confirm;
  const passwordsMismatch = confirm.length > 0 && password !== confirm;

  // ─── Shared brand header ───────────────────────────────────────────────────
  function renderBrandHeader() {
    return (
      <div className="mb-6 flex flex-col items-center justify-center text-center">
        <div className="flex items-center gap-3 mb-2">
          {logoUrl ? (
            <div
              className="flex h-[42px] w-[42px] shrink-0 items-center justify-center rounded-xl shadow-md ring-1 ring-white/10 border overflow-hidden"
              style={{ borderColor: primaryColor }}
            >
              <img src={logoUrl} alt={`${appName} logo`} className="h-full w-full object-contain" />
            </div>
          ) : (
            <BrandLogo
              size={42}
              showStatusDot={false}
              primaryColor={primaryColor}
              accentColor={accentColor}
            />
          )}
          <span className="text-xl font-bold tracking-tight text-foreground">{appName}</span>
        </div>
      </div>
    );
  }

  // ─── Loading skeleton ──────────────────────────────────────────────────────
  if (phase === 'loading') {
    return (
      <main className="relative flex min-h-screen w-full items-center justify-center overflow-x-hidden bg-background px-4 py-8">
        <div
          aria-hidden
          className="pointer-events-none absolute -top-32 left-1/2 -translate-x-1/2 size-[360px] sm:size-[500px] rounded-full blur-[100px]"
          style={{ backgroundColor: `${primaryColor}1a` }}
        />
        <div
          aria-hidden
          className="pointer-events-none absolute -bottom-32 right-1/4 size-[280px] sm:size-[420px] rounded-full blur-[90px]"
          style={{ backgroundColor: `${accentColor}26` }}
        />
        <div className="relative z-10 w-full max-w-[420px] mx-auto animate-in fade-in duration-300">
          {renderBrandHeader()}
          <div className="rounded-2xl border border-border/80 bg-surface/90 backdrop-blur-md p-6 sm:p-8 shadow-xl shadow-black/5 space-y-5">
            <div className="text-center space-y-2">
              <div className="h-6 w-48 rounded-md bg-muted animate-pulse mx-auto" />
              <div className="h-4 w-64 rounded bg-muted/60 animate-pulse mx-auto" />
            </div>
            <div className="space-y-3 pt-2">
              <div className="h-10 rounded-lg bg-muted/40 animate-pulse" />
              <div className="h-10 rounded-lg bg-muted/40 animate-pulse" />
            </div>
            <div className="h-10 rounded-lg bg-muted/30 animate-pulse" />
          </div>
        </div>
      </main>
    );
  }

  // ─── Error state ───────────────────────────────────────────────────────────
  if (phase === 'error') {
    return (
      <main className="relative flex min-h-screen w-full items-center justify-center overflow-x-hidden bg-background px-4 py-8">
        <div
          aria-hidden
          className="pointer-events-none absolute -top-32 left-1/2 -translate-x-1/2 size-[360px] rounded-full blur-[100px]"
          style={{ backgroundColor: `${primaryColor}1a` }}
        />
        <div
          aria-hidden
          className="pointer-events-none absolute -bottom-32 right-1/4 size-[280px] rounded-full blur-[90px]"
          style={{ backgroundColor: `${accentColor}26` }}
        />
        <div className="relative z-10 w-full max-w-[420px] mx-auto animate-in fade-in zoom-in-95 duration-300">
          {renderBrandHeader()}
          <div className="rounded-2xl border border-destructive/30 bg-surface/90 backdrop-blur-md p-6 sm:p-8 shadow-xl shadow-black/5">
            <div className="flex flex-col items-center text-center gap-4">
              <div className="flex h-14 w-14 items-center justify-center rounded-full bg-destructive/10 ring-1 ring-destructive/20">
                <XCircle className="size-7 text-destructive" />
              </div>
              <div>
                <h1 className="text-lg font-bold text-foreground">Invitation Link Invalid</h1>
                <p className="mt-2 text-sm text-muted-foreground leading-relaxed">{tokenError}</p>
              </div>
              <Button
                variant="outline"
                className="w-full mt-2 rounded-lg"
                onClick={() => void router.navigate({ to: '/login' })}
              >
                Back to Sign In
              </Button>
            </div>
          </div>
        </div>
      </main>
    );
  }

  // ─── Success state ─────────────────────────────────────────────────────────
  if (phase === 'success') {
    return (
      <main className="relative flex min-h-screen w-full items-center justify-center overflow-x-hidden bg-background px-4 py-8">
        <div
          aria-hidden
          className="pointer-events-none absolute -top-32 left-1/2 -translate-x-1/2 size-[360px] rounded-full blur-[100px]"
          style={{ backgroundColor: `${primaryColor}1a` }}
        />
        <div
          aria-hidden
          className="pointer-events-none absolute -bottom-32 right-1/4 size-[280px] rounded-full blur-[90px]"
          style={{ backgroundColor: `${accentColor}26` }}
        />
        <div className="relative z-10 w-full max-w-[420px] mx-auto animate-in fade-in zoom-in-95 duration-300">
          {renderBrandHeader()}
          <div className="rounded-2xl border border-border/80 bg-surface/90 backdrop-blur-md p-6 sm:p-8 shadow-xl shadow-black/5">
            <div className="flex flex-col items-center text-center gap-5">
              <div
                className="flex h-16 w-16 items-center justify-center rounded-full ring-2 shadow-lg"
                style={{
                  backgroundColor: `${primaryColor}15`,
                  boxShadow: `0 0 24px ${primaryColor}33`,
                }}
              >
                <CheckCircle2 className="size-8" style={{ color: primaryColor }} />
              </div>
              <div>
                <h1 className="text-xl font-bold text-foreground">Account Activated! 🎉</h1>
                <p className="mt-2 text-sm text-muted-foreground leading-relaxed">
                  Welcome to <strong>{appName}</strong>
                  {inviteInfo ? `, ${inviteInfo.first_name}` : ''}! Your account is now active.
                  Sign in below to get started.
                </p>
              </div>
              <Button
                id="activate-go-to-login"
                className="w-full h-10 font-semibold rounded-lg shadow-sm"
                style={{ backgroundColor: primaryColor }}
                onClick={() => void router.navigate({ to: '/login' })}
              >
                Sign In to Your Account
              </Button>
            </div>
          </div>
        </div>
      </main>
    );
  }

  // ─── Main form (ready / submitting) ────────────────────────────────────────
  const isSubmitting = phase === 'submitting';

  return (
    <main
      className="relative flex min-h-screen w-full items-center justify-center overflow-x-hidden bg-background px-4 py-8 sm:px-6 lg:px-8"
      role="main"
    >
      {/* Ambient blobs */}
      <div
        aria-hidden
        className="pointer-events-none absolute -top-32 left-1/2 -translate-x-1/2 size-[360px] sm:size-[500px] rounded-full blur-[100px] sm:blur-[140px] transition-colors duration-700"
        style={{ backgroundColor: `${primaryColor}1a` }}
      />
      <div
        aria-hidden
        className="pointer-events-none absolute -bottom-32 right-1/4 size-[280px] sm:size-[420px] rounded-full blur-[90px] sm:blur-[120px] transition-colors duration-700"
        style={{ backgroundColor: `${accentColor}26` }}
      />

      <div className="relative z-10 w-full max-w-[420px] mx-auto animate-in fade-in zoom-in-95 duration-200">
        {renderBrandHeader()}

        {/* Card */}
        <div className="rounded-2xl border border-border/80 bg-surface/90 backdrop-blur-md p-6 sm:p-7 shadow-xl shadow-black/5">
          {/* Card header */}
          <div className="pb-5 text-center">
            <div
              className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-xl ring-1 ring-white/10 shadow-md"
              style={{ backgroundColor: `${primaryColor}20` }}
            >
              <ShieldCheck className="size-6" style={{ color: primaryColor }} />
            </div>
            <h1 className="text-xl font-bold tracking-tight text-foreground">Set Your Password</h1>
            {inviteInfo ? (
              <p className="mt-1.5 text-xs text-muted-foreground leading-relaxed">
                Welcome,{' '}
                <span className="font-semibold text-foreground">
                  {inviteInfo.first_name} {inviteInfo.last_name}
                </span>
                !<br />
                Choose a secure password for{' '}
                <span className="font-medium">{inviteInfo.email}</span>
              </p>
            ) : (
              <p className="mt-1.5 text-xs text-muted-foreground">
                Choose a secure password to activate your account.
              </p>
            )}
          </div>

          <form
            onSubmit={(e) => void handleSubmit(e)}
            className="space-y-4"
            noValidate
            aria-label="Account Activation Form"
          >
            {/* Password field */}
            <div className="space-y-1.5">
              <Label htmlFor="activate-password" className="text-xs font-semibold">
                New Password
              </Label>
              <div className="relative">
                <Input
                  id="activate-password"
                  name="password"
                  type={showPassword ? 'text' : 'password'}
                  autoComplete="new-password"
                  autoFocus
                  required
                  placeholder="Choose a strong password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  disabled={isSubmitting}
                  className="h-10 pr-10 text-[13.5px] rounded-lg bg-muted/30 focus:bg-surface transition-all font-sans"
                  aria-required="true"
                />
                <button
                  type="button"
                  id="activate-toggle-password"
                  onClick={() => setShowPassword((v) => !v)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground focus:outline-none focus-visible:ring-2 focus-visible:ring-primary rounded p-0.5 transition-colors cursor-pointer"
                  aria-label={showPassword ? 'Hide password' : 'Show password'}
                  tabIndex={0}
                >
                  {showPassword ? (
                    <EyeOff className="size-4" aria-hidden />
                  ) : (
                    <Eye className="size-4" aria-hidden />
                  )}
                </button>
              </div>

              {/* Strength bar */}
              {password.length > 0 && (
                <div className="space-y-1 pt-0.5">
                  <div className="flex gap-1">
                    {[1, 2, 3, 4].map((i) => (
                      <div
                        key={i}
                        className="h-1 flex-1 rounded-full transition-all duration-300"
                        style={{
                          backgroundColor: i <= strength.score ? strength.color : 'hsl(var(--muted))',
                          opacity: i <= strength.score ? 1 : 0.4,
                        }}
                      />
                    ))}
                  </div>
                  {strength.label && (
                    <p className="text-[11px] font-medium" style={{ color: strength.color }}>
                      {strength.label} password
                    </p>
                  )}
                </div>
              )}
            </div>

            {/* Confirm password */}
            <div className="space-y-1.5">
              <Label htmlFor="activate-confirm" className="text-xs font-semibold">
                Confirm Password
              </Label>
              <div className="relative">
                <Input
                  id="activate-confirm"
                  name="confirm_password"
                  type={showConfirm ? 'text' : 'password'}
                  autoComplete="new-password"
                  required
                  placeholder="Re-enter your password"
                  value={confirm}
                  onChange={(e) => setConfirm(e.target.value)}
                  disabled={isSubmitting}
                  className="h-10 pr-10 text-[13.5px] rounded-lg bg-muted/30 focus:bg-surface transition-all font-sans"
                  aria-required="true"
                  aria-invalid={passwordsMismatch}
                />
                <button
                  type="button"
                  id="activate-toggle-confirm"
                  onClick={() => setShowConfirm((v) => !v)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground focus:outline-none focus-visible:ring-2 focus-visible:ring-primary rounded p-0.5 transition-colors cursor-pointer"
                  aria-label={showConfirm ? 'Hide confirmation' : 'Show confirmation'}
                  tabIndex={0}
                >
                  {showConfirm ? (
                    <EyeOff className="size-4" aria-hidden />
                  ) : (
                    <Eye className="size-4" aria-hidden />
                  )}
                </button>
              </div>
              {passwordsMatch && (
                <p className="text-[11px] font-medium text-emerald-500 flex items-center gap-1">
                  <CheckCircle2 className="size-3" /> Passwords match
                </p>
              )}
              {passwordsMismatch && (
                <p className="text-[11px] font-medium text-destructive flex items-center gap-1">
                  <XCircle className="size-3" /> Passwords do not match
                </p>
              )}
            </div>

            {/* Error banner */}
            {submitError && (
              <div
                id="activate-error"
                role="alert"
                aria-live="assertive"
                className="rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-xs font-medium text-destructive animate-in fade-in duration-150"
              >
                {submitError}
              </div>
            )}

            {/* Hint */}
            <p className="text-[11px] text-muted-foreground leading-relaxed">
              Minimum 8 characters. Use uppercase, numbers, and symbols for a stronger password.
            </p>

            {/* Submit */}
            <Button
              id="activate-submit-btn"
              type="submit"
              className="w-full h-10 font-semibold rounded-lg shadow-sm transition-all cursor-pointer flex items-center justify-center gap-2"
              disabled={isSubmitting || passwordsMismatch}
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="size-4 animate-spin" aria-hidden />
                  <span>Activating…</span>
                </>
              ) : (
                <span>Activate My Account</span>
              )}
            </Button>
          </form>
        </div>

        {/* Footer */}
        <p className="mt-6 text-center text-xs text-muted-foreground/80">
          {appName} Enterprise Security
        </p>
      </div>
    </main>
  );
}
